
#### General run settings ####
# Note that the simulations to be evaluted and the benchmark specific settings are define in the blocks below this one.
Settings:

  new_name: "CRUJRA_v4.1.2" # remove
  old_name: "CRUNCEP_v4.1" # change to "baseline"
  reference_simulation: "CRUNCEP_v4.1"
  data_directory: "/data/shared/Tellus"
  land_cover_file: "/data/mforrest/LandUseLandCover/LUH2_GCP2019/lu_1549_2019_luh2_aggregate_sum2x2_midpoint_nourban_gcp2019_2019_10_22.txt"


  do_maps: TRUE
  analysis_version: "tellus_v1.5_dev"
  # quick read switch 
  quick_read: FALSE
  # quick read autodelete switch, if TRUE previous file will be deleted and recreated 
  quick_read_autodelete: FALSE
  # do verbose reads - this makes a lot of printed output which will appear in the report, only enable for developing/debugging the reading code
  verbose_read: FALSE
  # do publication plots
  doPublicationPlots: FALSE
  # plot maps (turn off to save time if they are not needed)
  doMapPlots: TRUE
  # summary periods
  summary_periods: [ [1961, 1990],
                     [1990, 2000]]
  # Spatial extent - note that this only applies to some benchmarks - typically the spatially explicit global ones
  # it will be ignored for benchmarks such as the regrowth and Pan forest biomass benchmarks
  # spatial extent (can be a raster:: extent or a two column data.frame of gridcells), set to NULL for no subsetting
  spatial_extent:  NULL
  # spatial_extent <- subset_1600_gridcells 
  # spatial_extent <- extent(c(xmin: -10, ymin: 35, xmax: 35, ymax : 72)) 
    
  # set to a string to describe the spatial subset and use "Global" if not cropping area
  spatial_extent_id: "Global" 
  #spatial_extent_id <- "The1600"
  # spatial_extent_id <- "Europe" 
    
  # Standard plot formatting arguments
  num_cols: 1
  map_overlay: "coastlines"
  stats_lon: -130
  stats_lat: -20
  map_text_multiplier: 2.5
  map_annotation_text_size: 7

#### Simulations ####
# Here specify the simulations to benchmark  
Simulations:
  # Indents at this level define a unique ID for this model
  CRUNCEP_v4.1: 
    # Each of these three things *must* be defined for each model
    name: "CRUNCEP_v4.1" 
    dir: "/dmz/home/mforrest/GuessRuns/Tellus_dev/CRUNCEP_v4.1"
    format: "GUESS"
  CRUJRA_v4.1.2:
    name: "CRUJRA_v4.1.2"
    dir: "/dmz/home/mforrest/GuessRuns/Tellus_dev/CRUJRA_v4.1.2"
    format: "GUESS"

#### Benckmarks ####
# Here specify the details of each benchmark
Benchmarks:
  
  # Indents at this level define the ID of a benchmark
  # Global Carbon Project benchmark
  GCP_NBP:
    # Standard required benchmark settings
    run_benchmark: TRUE
    name: "GCP NBP"
    description: "Global Carbon Project Net Biome Productivity"
    first.year: 2005 # update when comparing to newer runs
    last.year: 2014 # update when comparing to newer runs
    simulation: "tellus"
    guess_var: "cflux"
    guess_layers: "NBP"
    unit: "kg m^-2^ y^-1^"
    agg.unit: "PgC y^-1^"
    metrics: [ "r2", "RMSE" ]
    # NOTE: Special case here, no dataset provide as DGVMTools::Source object because the benchmark reads raw GCP Excel file 
    # Custom: For reading from the GCP Clobal Carbon Budget spreadsheet, these can/will change with a newer version
    sheet: "Global Carbon Budget"
    skip_rows: 21
    nyears_GCP: 65
    
  # PNV Biomes
  PNV_Biomes:
    # Standard required benchmark settings
    run_benchmark: TRUE
    name: "Global biomes"
    description: "Smith et al 2014 biomes vs PNV from Haxeltine and Prentince 1992"
    simulation: [ "global", "tellus" ]
    guess_var: "lai"
    guess_layers: "Smith2014" # not strictly speaking a layer, but the function interprets this as the classification and the name of the data file
    first.year: 1960
    last.year: 1990
    year.aggregate.method: "mean"
    unit: ""
    agg.unit: ""
    metrics: ""
    datasets:
      HandP_biomes:
        name: "HandP_biomes"
        format: "NetCDF"
        dir: "biomes/HandP_biomes"

  # FLUXNET benchmark
  FLUXNET:
    # Standard required benchmark settings
    run_benchmark: FALSE
    name: "FLUXNET"
    description: "FLUXNET"
    simulation: "fluxnet"
    guess_var: [ "dgpp", "dnee", "dreco" ]
    guess_layers: [ "Total", "NEE", "Reco"]
    unit: "kgC/m^2"
    agg.unit: "Not Used"
    datasets: 
      FLUXNET:
        name: "FLUXNET"
        format: "FLUXNET"
        dir: "FLUXNET_sites"
    metrics: ""
    # FLUXNET specific settings
    do_fluxes: ["GPP", "Reco", "NEE"]     # possibilities are GPP, Reco and NEE
    measurement_days_reqrd: 3             # out of 5 days, recommend 3
